export default {
  title:'dark',    
  colors:{       
    priority_colors:{
      normals:'#F0F1F7',      
      urgents:'#FEC400',
      important:'#29CC97',
      high_priority:'#C8372D'
    },
    status_colors:{
      progress:'#0091FF',
      opens:'#9FA2B4',
      waitings:'#C8372D',
      solveds:'#29CC97'
    },
    layout_colors:{
      primary:'#1B1F38',
      secondary:'#252A48',
      tertiary:'#313862',
      black_texts:'##FFFF',
      light_texts:'#9FA2B4'
    },
    others:{
      normals:'#2F88A0',
      light_texts:'#C5C7CD',
      gradient:'#15647A',
      line_color:'#E6E6E6',
      hover_menu:'#C4C4C4',
    }
  }
}