export default {
  title:'light',    
  colors:{       
    priority_colors:{
      normals:'#F0F1F7',      
      urgents:'#FEC400',
      important:'#29CC97',
      high_priority:'#C8372D',      
    },
    status_colors:{
      progress:'#0091FF',
      opens:'#9FA2B4',
      waitings:'#C8372D',
      solveds:'#29CC97'
    },
    layout_colors:{
      primary:'#FFFFFF',
      secondary:'#F7F8FC',
      tertiary:'#2F88A0',
      black_texts:'#252733',
      light_texts:'#9FA2B4'
    },
    others:{
      normals:'#2F88A0',
      light_texts:'#DFE0EB',
      gradient:'#27A6B4',
      line_color:'#E6E6E6',
      hover_menu:'#DFE0EB',
      calendar_pick:'#15647A',
    }
  }
}